### ISSUE TITLE
Errors using Java 8, Spigot 1.8.9.

### ISSUE THREAD

**Issue by TheIntelloBox** [Rayzr522/DecoHeads#5] opened 2016-10-15 20:31 UTC
`[22:30:31] [Server thread/ERROR]: Could not pass event InventoryClickEvent to DecoHeads v1.3
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1630) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
    at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
    at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NullPointerException
    at com.rayzr522.decoheads.DHListener.onInventoryClick(DHListener.java:39) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor549.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
    ... 15 more`

**Comment by foxfirecodes** [comment] 2016-10-15 21:38
Sorry, this is actually caused by something I didn't know about at the time of writing the plugin (originally). I assume this happened while you were in creative?

**Comment by TheIntelloBox** [comment] 2016-10-16 08:13
Yes. :(

**Comment by foxfirecodes** [comment] 2016-10-16 12:13
Sorry for the inconvenience. I will fix it tomorrow and then give you a dev build. 

Bukkit is stupid sometimes, and at the time of writing the plugin I didn't know that. I'll fix it up for ya :D

**Comment by TheIntelloBox** [comment] 2016-10-16 13:15
Oh okay, thanks ! :D And when do you think, the 1.4 will be released ? :D (yeah I'm so impatient xD)

Thanks a lot ! :D

**Comment by foxfirecodes** [comment] 2016-10-16 18:26
Not sure, tbh I haven't even touched it in a month or two. Now that I have some stuff to fix / feature requests from you I will start working on it again. 

So probably a week or two, I work pretty quick :wink:

**Comment by foxfirecodes** [comment] 2016-10-16 18:28
Well I might not the categories system done at that point... it depends, I may or may not be able to modify the GUI to allow that functionality. We'll see :grin:

**Comment by TheIntelloBox** [comment] 2016-10-16 18:41
Oh yeahs thanks ! :D 
Okay good luck ! :) Fantastic plugin, the best I saw.

**Comment by foxfirecodes** [comment] 2016-10-16 19:20
Thank you :grin:

People like you are what make developing worth it :smile:

**Comment by TheIntelloBox** [comment] 2016-10-17 17:01
:D.

**Comment by TheIntelloBox** [comment] 2016-10-31 19:01
Any news ? :D

**Comment by foxfirecodes** [comment] 2016-11-04 20:21
Sorry! I've been busy with my dev group, and the last few days I've been (shudder) cleaning out my hard drive. I used to have only 98GB of free space, now I have something like 240GB!

Anyways, I should have more free time, I'll try and get to this in the next 7 days. Thanks for your patience :P

**Comment by TheIntelloBox** [comment] 2016-11-04 21:27
Okay, no problem. :dagger: 

Thaanks. You're welcome. :D

**Comment by foxfirecodes** [comment] 2016-11-06 01:33
I've fixed this specific issue and localized the messages/text in the plugin into a config file. I still need to tweak a couple things, but after that I'll release v1.3.1. It should be out on Monday. 

If you know how to use Maven, you can compile itself by simply cloning the project, going into the project directory with your terminal/command prompt, and running `mvn clean package`. 

Do keep in mind that it's not ready for release yet, and I will most likely change some things with the localization config. I'm not a huge fan of the current formatting. 

Also just one more note, I will be changing to use Java 8 after this release. I'm sorry if some people don't have Java 8, but it is ridiculous to ignore the huge benefit to me as a developer just for a few people, especially since nearly all server hosts are using Java 8 now and people with homebrew servers can upgrade in a matter of 15-Ish minutes. 

Big wall o' text for ya :P

**Comment by TheIntelloBox** [comment] 2016-11-06 09:49
Hello,

I don't know how to use Maven. :( I will wait for the release so. ;) 
I use Java 8 so this isn't a problem for me. :D 

Thanks ! :)

**Comment by foxfirecodes** [comment] 2016-11-07 19:56
Fixed in v1.3.1

**Closed as completed by foxfirecodes** 2016-11-07 19:56 UTC
Labels: bug

**Comment by TheIntelloBox** [comment] 2016-11-08 16:07
Yep.
