### ISSUE TITLE
Bug !

### ISSUE THREAD

**Issue by TheIntelloBox** [Rayzr522/DecoHeads#10] opened 2016-11-11 21:11 UTC
Hello,

I have a bug.
Errors : http://hastebin.com/emepopomam.bash
Using Java 8 & Spigot 1.8.8. :D

When I write /deco, and when I click on the button "Next Page", it's close the inventory, so we can't go to the page 2, 3, etc.

Thanks ! :D

**Comment by foxfirecodes** [comment] 2016-11-11 21:13
Really? lemme test this...

**Comment by TheIntelloBox** [comment] 2016-11-11 21:15
Okay. :D I corrected my issue, I did a fault, sorry. :D

**Comment by foxfirecodes** [comment] 2016-11-11 21:38
Hmmm, the error doesn't tell me what line of code it is, and I can't reproduce it. Try restarting your server and then reproducing it. If you manage to reproduce it, send me the new error.

Thanks for your patience :)

**Comment by TheIntelloBox** [comment] 2016-11-11 21:55
http://hastebin.com/obagefajeq.bash
Finally. :D

**Comment by TheIntelloBox** [comment] 2016-11-12 20:37
Hello, so ? xD

**Comment by foxfirecodes** [comment] 2016-11-12 22:04
I can't figure out the but. It doesn't seem physically possible...

I can't seem to reproduce the bug. Can you try reinstalling DecoHeads?

**Comment by TheIntelloBox** [comment] 2016-11-13 09:53
Doesn't work. x)

**Comment by foxfirecodes** [comment] 2016-11-13 18:55
Have you modified the heads.yml at all?

**Comment by TheIntelloBox** [comment] 2016-11-13 19:23
Nop. x)
heads.yml : http://hastebin.com/lolicunipu.pas

**Comment by foxfirecodes** [comment] 2016-11-14 15:00
Can you try running it on a fresh server with no other plugins installed, and then slowly add in the plugins you have on your current server? I believe it has something to do with another plugin, since the error that is occurring should be... impossible.

Also are you using Minecraft 1.8?

**Comment by TheIntelloBox** [comment] 2016-11-14 18:10
Minecraft 1.8.8.
Soon 1.11.

**Comment by foxfirecodes** [comment] 2016-11-14 18:19
Hmm. I'll try reproducing the bug in 1.8

Any specific reason why you haven't upgraded to 1.10 yet?

**Comment by foxfirecodes** [comment] 2016-11-14 18:44
Tested in 1.8 and 1.8.8 with no crashes. I'm still extremely confused as to how this could happen.

**Comment by TheIntelloBox** [comment] 2016-11-14 19:00
The plugin doesn't crash. We cannot go to the page 2, etc. I do a video if you want.
Before this problem, I wrote /heads search Pokemon.

**Comment by foxfirecodes** [comment] 2016-11-14 19:03
Sorry, not crash, but I didn't have any problems. It worked 100% as expected. I'll try `/heads search Pokemon` shortly to see if that changes anything.

**Comment by TheIntelloBox** [comment] 2016-11-14 19:06
Okay. :(

**Comment by foxfirecodes** [comment] 2016-11-18 22:58
Can't seem to figure this out. If you could do a video that'd be great.

**Comment by TheIntelloBox** [comment] 2016-11-19 09:55
I will do it.

**Comment by TheIntelloBox** [comment] 2016-11-19 22:51
Okay I found the bug.

I deleted the old folder, restarted my server. This worked fine. After, I uploaded the old messages.yml into the new, I wrote /decoheads reload, and now it's doesn't work !
My messages.yml : http://hastebin.com/hiveyokibe.http

Thanks ! :D

**Comment by foxfirecodes** [comment] 2016-11-19 23:49
Alright, figured out what the problem is but I won't be able to fix it till tomorrow. For now just make sure that the next button contains the literal word "Next" (exactly like that except minus the quotations)

When I had written the code originally I hadn't written the GUI listener in a flexible manner that would allow configurable text. I made the text configurable, but I forgot to change that one bit of the code.

**Comment by TheIntelloBox** [comment] 2016-11-20 10:26
Oh okay. :D 
When will it be fixed ?

**Comment by foxfirecodes** [comment] 2016-11-20 23:30
https://ci-perceive.rhcloud.com/job/DecoHeads/3/artifact/target/DecoHeads-1.3.1.jar

Should fix your problem

**Comment by foxfirecodes** [comment] 2016-11-21 16:47
That was a temporary fix for v1.3, this isn't even a problem anymore in v1.4 since I completely redid the GUI system anyways. Since v1.4 is going to be released today or tomorrow I'm marking this as closed.

**Closed as completed by foxfirecodes** 2016-11-21 16:47 UTC
